before_script:
    - date
    - uname -a
    - printenv | sort

parks_protection_postman:
    image:
        name: postman/newman_alpine33
        entrypoint: [""]
    script:
        - cd test
        - newman run postman.json